"""Tools for the Remediation Expert agent: generating scripts, mappings, and JIRA drafts."""

from langchain_core.tools import tool
import json

@tool
def generate_sql_fix(table_name: str, issue_description: str, recommended_fix_logic: str = "") -> str:
    """Generate a template SQL fix script (UPDATE or INSERT) to correct a data anomaly in a Snowflake target.
    table_name: The table where the break originates.
    issue_description: A short description of the problem (e.g. 'Null counterparty LEI on Fed Funds').
    recommended_fix_logic: Optional specific SQL logic, if known (e.g., 'COALESCE(lei, 'UNKNOWN')').
    """
    logic = recommended_fix_logic if recommended_fix_logic else "-- Identify and replace invalid values"
    
    script = f"-- RECONX AUTOGENERATED FIX MITIGATION\n"
    script += f"-- Target: {table_name}\n"
    script += f"-- Context: {issue_description}\n\n"
    script += f"BEGIN;\n"
    script += f"  UPDATE {table_name}\n"
    script += f"  SET /* TODO: Insert correct mapping from {logic} */\n"
    script += f"  WHERE /* TODO: Insert identifying condition for the anomaly */;\n"
    script += f"COMMIT;\n"
    
    return script

@tool
def suggest_axiom_mapping(report_form: str, filter_or_rule: str, current_value: str, target_value: str) -> str:
    """Propose an AxiomSL mapping adjustment for a report (e.g. FR2052a).
    report_form: The report name (e.g. FR2052a, FR2590).
    filter_or_rule: The name of the mapping lookup or filter logic.
    current_value: The value currently failing the map.
    target_value: The desired output value for the map.
    """
    suggestion = f"## AxiomSL Mapping Adjust Request\n\n"
    suggestion += f"- **Report Context**: {report_form}\n"
    suggestion += f"- **Target Rule/Dictionary**: {filter_or_rule}\n"
    suggestion += f"- **Current Unmapped Source**: `{current_value}`\n"
    suggestion += f"- **Proposed Target Output**: `{target_value}`\n\n"
    suggestion += f"> *Action*: Add a new dictionary entry mapping `{current_value}` to `{target_value}` in the `{filter_or_rule}` lookup.\n"
    
    return suggestion

@tool
def draft_jira_ticket(summary: str, details: str, break_type: str, priority: str = "Medium") -> str:
    """Draft payload for a JIRA ticket to log a break trace for a data engineering team.
    summary: Ticket title.
    details: The full break context.
    break_type: E.g., 'Reference Data Missing', 'Unmapped Product'.
    priority: "High", "Medium", "Low".
    """
    ticket_payload = {
        "fields": {
            "project": {"key": "RECON"},
            "summary": f"[{break_type}] {summary}",
            "description": details,
            "issuetype": {"name": "Bug"},
            "priority": {"name": priority},
            "labels": ["reconx-generated", "break-remediation"]
        }
    }
    return f"Prepared JIRA Payload:\n```json\n{json.dumps(ticket_payload, indent=2)}\n```"

TOOLS = [generate_sql_fix, suggest_axiom_mapping, draft_jira_ticket]